//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t __libc_csu_fini(void);
int64_t __libc_csu_init(int64_t a1, int64_t a2, int64_t a3);
int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t add(int32_t * a1, char a2);
int64_t deregister_tm_clones(void);
int64_t frame_dummy(void);
int32_t function_1030(char * format, ...);
void function_1040(int64_t * d);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x1130; // 0x3de8
int64_t g2 = 0x10f0; // 0x3df0
int64_t g3 = 0; // 0x3ff8
int64_t g4 = 0; // 0x4030
int32_t g5;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x3fe8 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g5;
    }
    // 0x1016
    return result;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(char * format, ...) {
    // 0x1030
    return printf(format);
}

// Address range: 0x1040 - 0x1046
void function_1040(int64_t * d) {
    // 0x1040
    __cxa_finalize(d);
}

// Address range: 0x1050 - 0x107f
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x1050
    int64_t v1; // 0x1050
    __libc_start_main(0x1160, (int32_t)a4, (char **)&v1, (void (*)())0x11c0, (void (*)())0x1230, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1080 - 0x10a9
int64_t deregister_tm_clones(void) {
    // 0x1080
    return &g4;
}

// Address range: 0x10b0 - 0x10e9
int64_t register_tm_clones(void) {
    // 0x10b0
    return 0;
}

// Address range: 0x10f0 - 0x1129
int64_t __do_global_dtors_aux(void) {
    // 0x10f0
    if (*(char *)&g4 != 0) {
        // 0x1128
        int64_t result; // 0x10f0
        return result;
    }
    // 0x10fd
    if (g3 != 0) {
        // 0x110b
        __cxa_finalize((int64_t *)*(int64_t *)0x4028);
    }
    int64_t result2 = deregister_tm_clones(); // 0x1117
    *(char *)&g4 = 1;
    return result2;
}

// Address range: 0x1130 - 0x1139
int64_t frame_dummy(void) {
    // 0x1130
    return register_tm_clones();
}

// Address range: 0x1140 - 0x115c
int64_t add(int32_t * a1, char a2) {
    // 0x1140
    int64_t v1; // 0x1140
    return v1 + (int64_t)a2 & 0xffffffff;
}

// Address range: 0x1160 - 0x11bb
int main(int argc, char ** argv) {
    int32_t v1 = 1; // bp-16, 0x116f
    int64_t v2 = add(&v1, 2); // 0x1182
    add(&v1, 2);
    printf("%d\n", v2 & 0xffffffff);
    return 0;
}

// Address range: 0x11c0 - 0x1225
int64_t __libc_csu_init(int64_t a1, int64_t a2, int64_t a3) {
    int64_t result = _init(); // 0x11ec
    if ((int64_t)&g2 - (int64_t)&g1 >> 3 == 0) {
        // 0x1216
        return result;
    }
    int64_t v1 = 0; // 0x11f5
    while (v1 + 1 != (int64_t)&g2 - (int64_t)&g1 >> 3) {
        // 0x1200
        v1++;
    }
    // 0x1216
    return result;
}

// Address range: 0x1230 - 0x1235
int64_t __libc_csu_fini(void) {
    // 0x1230
    int64_t result; // 0x1230
    return result;
}

// Address range: 0x1238 - 0x1245
int64_t _fini(void) {
    // 0x1238
    int64_t result; // 0x1238
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (9.4.0)
// Detected functions: 13

