//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>

// ------------------- Function Prototypes --------------------

int64_t add(int32_t * a1, int64_t a2);

// ------------------------ Functions -------------------------

// Address range: 0x401126 - 0x401141
int64_t add(int32_t * a1, int64_t a2) {
    // 0x401126
    return (0x100000000000000 * a2 >> 56) + (int64_t)a1 & 0xffffffff;
}

// Address range: 0x401141 - 0x4011a1
int main(int argc, char ** argv) {
    int32_t v1 = 1; // bp-32, 0x401149
    int64_t v2 = add(&v1, 2); // 0x401161
    add(&v1, 2);
    printf("%d\n", v2 & 0xffffffff);
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.1)
// Detected functions: 2

